### ISSUE TITLE
Notificaties

### ISSUE THREAD

**Issue by robbinbenard** [mach3builders/ui#3]
Ik kan geen manier vinden om de notifiy aan te roepen, zag dat het wel kon op een formulier met ajax submit.

Soms wil je ook custom iets maken en ui.notify({options}); kunnen gebruiken.

**Comment by PaulKruijt** [comment]
import {notifier} from '@mach3builders/ui/resources/assets/js/ui/Notifier'

notifier.show({
    type: 'success',
    body: 'Je bent lekker bezig!'
})
